// Hardhat 3 node:test (viem). Run with `bun run test:hardhat` (or
// `hardhat test`). Lives outside the bun smoke dir (test-unit/) and is excluded
// from tsc — it references viem contract types generated by `hardhat compile`.
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { network } from "hardhat";

const { viem, networkHelpers } = await network.create();

const FAUCET_AMOUNT = 1_000n * 10n ** 6n;
const FAUCET_COOLDOWN = 8 * 60 * 60; // 8 hours, seconds
const FAUCET_CAP = 10_000n * 10n ** 6n;

async function deploy() {
  const musd = await viem.deployContract("mUSD");
  return { musd };
}

describe("mUSD", () => {
  it("is named mUSD with 6 decimals", async () => {
    const { musd } = await networkHelpers.loadFixture(deploy);
    assert.equal(await musd.read.name(), "Autonoe Mock USD");
    assert.equal(await musd.read.symbol(), "mUSD");
    assert.equal(await musd.read.decimals(), 6);
  });

  it("faucet() mints the fixed amount to the caller", async () => {
    const { musd } = await networkHelpers.loadFixture(deploy);
    const [, alice] = await viem.getWalletClients();

    await musd.write.faucet({ account: alice.account });

    assert.equal(
      await musd.read.balanceOf([alice.account.address]),
      FAUCET_AMOUNT,
    );
    assert.equal(
      await musd.read.faucetMinted([alice.account.address]),
      FAUCET_AMOUNT,
    );
  });

  it("enforces the per-address cooldown", async () => {
    const { musd } = await networkHelpers.loadFixture(deploy);
    const [, alice] = await viem.getWalletClients();

    await musd.write.faucet({ account: alice.account });

    // Second claim before the cooldown elapses reverts.
    await assert.rejects(
      musd.write.faucet({ account: alice.account }),
      /faucet cooldown/,
    );

    // After the cooldown it succeeds again.
    await networkHelpers.time.increase(FAUCET_COOLDOWN);
    await musd.write.faucet({ account: alice.account });
    assert.equal(
      await musd.read.balanceOf([alice.account.address]),
      FAUCET_AMOUNT * 2n,
    );
  });

  it("enforces the lifetime faucet cap", async () => {
    const { musd } = await networkHelpers.loadFixture(deploy);
    const [, alice] = await viem.getWalletClients();

    const maxClaims = Number(FAUCET_CAP / FAUCET_AMOUNT);
    for (let i = 0; i < maxClaims; i++) {
      await musd.write.faucet({ account: alice.account });
      await networkHelpers.time.increase(FAUCET_COOLDOWN);
    }

    assert.equal(
      await musd.read.balanceOf([alice.account.address]),
      FAUCET_CAP,
    );
    // One more would exceed the cap.
    await assert.rejects(
      musd.write.faucet({ account: alice.account }),
      /faucet cap reached/,
    );
  });

  it("ownerMint() is owner-only", async () => {
    const { musd } = await networkHelpers.loadFixture(deploy);
    const [owner, alice, bob] = await viem.getWalletClients();

    await musd.write.ownerMint([bob.account.address, 5_000_000n], {
      account: owner.account,
    });
    assert.equal(
      await musd.read.balanceOf([bob.account.address]),
      5_000_000n,
    );

    await assert.rejects(
      musd.write.ownerMint([alice.account.address, 1n], {
        account: alice.account,
      }),
    );
  });
});
